application: its-hackademic
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  mime_type: text/html
  static_files: static/index.html
  upload: static/index.html

- url: /metadata/
  script: app.app

- url: /static/codelabs/(.*)/
  mime_type: text/html
  static_files: static/codelabs/\1/index.html
  upload: static/codelabs/.*/index.html

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|svg))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png|svg))
